### ISSUE TITLE
Better File management needed

### ISSUE THREAD

**Issue by TheGITofTeo997** [TheGITofTeo997/PokeProject#11]
The more we get on with the project and the more files we need to save. This is not an issue by itself, but we need to find a way to organize our files better, furthermore we need to find a way to distribute them better between the clients and the server. 

This is just an enhancement since the project could work without this.

**Comment by Drunper** [comment]
Placing file in the data folder i created seems fine for the moment. Creating folders for the various files (gifs, pokemon and type initializers) proved to be a solid approach, with the right methods.
