### ISSUE TITLE
PokeChooserFrame GIF attribute issue

### ISSUE THREAD

**Issue by TheGITofTeo997** [TheGITofTeo997/PokeProject#13]
Now that Pokemon objects are linked to their GIFs, we don't have anymore to write the resource path of the GIF in the PokeChooserFrame. Instead, we should get it from the Pokemon class getter for that attribute.

The problem here is that obviously, we have no Pokemon object loaded in the PokeChooserFrame, since it is part of the view, and because of that, we are not able to invoke the getter for the Pokemon class. 

We need to find a way to invoke that getter from the view, but without passing the complete TreeMap, since doing this would break down things a lot.

**Comment by Drunper** [comment]
With one of the latest commit the issue can be considered solved, although we can still improve it.
