### ISSUE TITLE
pkClient as constructor argument for PokeChooserFrame

### ISSUE THREAD

**Issue by TheGITofTeo997** [TheGITofTeo997/PokeProject#18]
In order to build a PokeChooserFrame instance we need to have the client under our control. 
As a temporary workaround we managed to build the PokeChooserFrame that requires a MainClient instance in its constructor. This is not safe at all and could lead to some serious violation, we need to find a way to improve and enhance this point.

**Comment by Drunper** [comment]
After a lot of thinking and studying, i've probably found a solution. I will implement it in the next few days.

**Comment by TheGITofTeo997** [comment]
This will probably be fixed with the new approach we are using. The client frame will be a unique frame and we will put many panels as we want on it, work will be done in future commits.

**Comment by Drunper** [comment]
This is not an issue anymore.
