### ISSUE TITLE
Better Queues management

### ISSUE THREAD

**Issue by Drunper** [TheGITofTeo997/PokeProject#19]
The problems we encountered with the queues' management is the result of my poor thinking. We need to look after this issue to avoid multiple for cycles in the code and have a better code readability and understanding.

**Comment by TheGITofTeo997** [comment]
@Drunper I think we are actually and partially fixing this avoiding the use of IdentifiedQueues for half of the client-server interface, however this is surely more improvable than this so, I suggest to leave this issue open.

**Comment by Drunper** [comment]
This issue has been fixed by removing unnecessary queues.
