### ISSUE TITLE
DRY approach in the project

### ISSUE THREAD

**Issue by Drunper** [TheGITofTeo997/PokeProject#20]
This issue is closely related to #11. We need to find a way to read objects and other things from file in a better and solid way. The current situation is horrible because if we want to add another pokemon we would need to add several code lines, both in the model and the view.

**Comment by TheGITofTeo997** [comment]
I don't know if we are currently in a state where we can close this issue, but i am almost completely sure situation has improved a lot. Decision left up to assignees.
