### ISSUE TITLE
selectedMove method in the mainServer class

### ISSUE THREAD

**Issue by Drunper** [TheGITofTeo997/PokeProject#22]
This method is partially implemented: if one of the clients wins, the program's behavior is unpredictable. Also, in case of winning, we need to optimise the code.

**Comment by TheGITofTeo997** [comment]
@Drunper this is a pretty old issue and many things have changed since the opening of it. Is this still a thing? If so feel free to leave it open.

**Comment by Drunper** [comment]
We will look to this issue the next friday, when we will reach a point where the method is invoked.

**Comment by TheGITofTeo997** [comment]
Since many things have changed from the opening of this issue, i would suggest to close it and to put all of our efforts in #27. However, this is not an issue anymore since moves are being selected correctly.
