### ISSUE TITLE
Complete Frame migration as soon as possible

### ISSUE THREAD

**Issue by TheGITofTeo997** [TheGITofTeo997/PokeProject#24]
We probably found a new approach that is supposed to fix our MVC problems. Server is fixed, but for client, since we don't want to get in the multiple controllers horrible world, we went for a cleaner and better new way: we will migrate all the old frames that dealt with the client in new panels, that will be part of the client view but in the *SAME* frame. This should fix most of the MVC problems that we encountered.

We need to to this migration as soon as possible in order to get on with the project.
Migration has already started while I am opening this issue, we will close this when the migration is completed.

**Comment by Drunper** [comment]
I'm commenting this just to say that PokeChooserPanel will be REALLY difficult to migrate, if we want to improve code solidity.

**Comment by TheGITofTeo997** [comment]
@Drunper we will see what we can do during the migration process, if we ecounter major problems we will open new issues.

**Comment by TheGITofTeo997** [comment]
@Drunper Albeit we still have a minor structural problem in PokeChooser (GIF drawing) the migration is basically complete, i will leave to you the decision to close this issue or to leave it open until we fix even that minor problem. We could open another issue for that anyway.

**Comment by Drunper** [comment]
With commit 6e51581 i should have completely resolved this issue.
