### ISSUE TITLE
Wrong data in message could lead to corrupted battlePanel setUp

### ISSUE THREAD

**Issue by TheGITofTeo997** [TheGITofTeo997/PokeProject#26]
With the new progresses and connection estabilished we ran into a major but occasional bug.
After pokeChooser selection something bad may happen and as soon as you reach battlePanel you may find that opponent's GIF is corrupt and/or invalid.

This is a serious bug since it compromises the whole battle: bad thing about it is that after many tests in the environment we were not able to recreate it, so it appears to happen randomly for some reason.

This is not a procedural bug since it doesn't prevent us to go further with the project, but needs to be fixed as soon as possible

**Comment by Drunper** [comment]
With the latest commit this issue should have been fixed. As always, further tests needed
