### ISSUE TITLE
ActionListeners for clients are growing exponentially each turn

### ISSUE THREAD

**Issue by TheGITofTeo997** [TheGITofTeo997/PokeProject#27]
As soon as we got the battle working we encountered a serious issue with the actionListeners implementation. Each turn attaches a *new* actionListener to the battlePanel and this results in a waste of memory and resources, there are also some damage calculation problems that we need to fix.

We need to find a way to remove the new listener every turn or we need a workaround listeners implementation.

**Comment by Drunper** [comment]
Issue fixed with latest commit.
