### ISSUE TITLE
Message sent from client is going out of bounds in the server queue (probably depending on #2)

### ISSUE THREAD

**Issue by TheGITofTeo997** [TheGITofTeo997/PokeProject#3]
After the changes we made in the latest commit (9fdc5d8) as of 24/01/2019 we encountered some heavy connection problems as mentioned in #2, and in addition to that we are not able to correctly carry a PKMessage from server to client, since the server returns an array out of bounds exception. 

We actually think that this issue is depending on #2, maybe if we solve that first, the message will be correctly handled.

So, because of that, i would suggest to investigate on #2 first and then take a look to this issue which will probably be easily solved.

**Comment by Drunper** [comment]
The method setupQueue() was not invoked anywhere. So the arraylists had 0 as size and this led to the issue.
