### ISSUE TITLE
Connection form does not hide on client when connected

### ISSUE THREAD

**Issue by TheGITofTeo997** [TheGITofTeo997/PokeProject#5]
In the new client GUI, after you entered the server IP in the form and you hit connect, the form does not disappear. 

We need to find a way to notice the view that the client has successfully connected

**Comment by Drunper** [comment]
Probably the problem is solved with commit ee9c4de.

**Comment by TheGITofTeo997** [comment]
I have personally tested commit (ee9c4de) and looks like the problem has been solved, we can close this issue for now.
