### ISSUE TITLE
MVC Model violation in the Project

### ISSUE THREAD

**Issue by TheGITofTeo997** [TheGITofTeo997/PokeProject#9]
Since we started working on the client view and the battle frame, we encountered some serious violation of the MVC model (mostly generated by the view). In particular:

- our view, the PokeChooserFrame, needs to notify the MainClient class (controller) that a Pokemon has been chosen
- the MainClient class needs to react to this event, and eventually execute the related command

We tried to implement ActionListener interface into the MainClient class, but we are still not able to point a target to it (you know who to thank for this). 

We eventually managed to link the button ActionListener to the MainClient class, but we are still not able to notify changes to it.

**Comment by TheGITofTeo997** [comment]
As of 11/02/2019 we implemented the ActionListener interface in the MainClient class. With this we are now able to listen to the action performed on the start button in the view. This *should not* violate the MVC developing model, however further tests will be done in the future. We can keep this as a solution now to make the project work.

We can consider this issue closed.

**Comment by Drunper** [comment]
Actually, this issue is not resolved yet. After thinking about, the issue got more serious.

**Comment by TheGITofTeo997** [comment]
This will probably be fixed with the new approach as described in #18. Please refer to that issue first for further info

**Comment by Drunper** [comment]
With the latest commits the issue is gradually being solved. The modelization of program's behavior is still something that i will do as soon as possibile, but for the rest (displaying pokemons, passing from one panel to another and so on) we are in a good position. The solution that i partially implemented is not the optimal one, i think, but it should respect the MVC pattern.

**Comment by TheGITofTeo997** [comment]
@Drunper We are gradually fixing this with minor workarounds, however i would leave this issue open until we completely fix this. If we get in a state where the program is working but still not perfect under MVC circumstances we can leave this issue open but we can remove the procedural label.

**Comment by Drunper** [comment]
As i worked further with the code i didn't find any other issue related to possible violations of MVC pattern. I removed the tag procedural, as it was explained above.

**Comment by TheGITofTeo997** [comment]
Since we basically fixed this, i would suggest to create a new pull request (thing that i am going to do asap), and merge the mvc_fix branch into the master one.

**Comment by Drunper** [comment]
This issue can be closed now. We just need to take extra care when we work with the view.
